// flow-typed signature: 8cf9071aecb0b306e7d92738bc57f802
// flow-typed version: <<STUB>>/cli-highlight_v^2.0.0/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cli-highlight'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cli-highlight' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cli-highlight/dist/cli' {
  declare module.exports: any;
}

declare module 'cli-highlight/dist/index' {
  declare module.exports: any;
}

declare module 'cli-highlight/dist/theme' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cli-highlight/dist/cli.js' {
  declare module.exports: $Exports<'cli-highlight/dist/cli'>;
}
declare module 'cli-highlight/dist/index.js' {
  declare module.exports: $Exports<'cli-highlight/dist/index'>;
}
declare module 'cli-highlight/dist/theme.js' {
  declare module.exports: $Exports<'cli-highlight/dist/theme'>;
}
